version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    hostname: localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
#      - "127.0.0.1:3005:3005"
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - SERVICES=sqs,sns,lambda,s3,cloudformation,cloudwatch,logs,iam
      #- LAMBDA_STAY_OPEN_MODE=0 # Set to 0 if you want to use hot-reloading 
      #- LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT=600 # 10 minutes?
      #- LAMBDA_DOCKER_NETWORK=bridge
      #- LAMBDA_DOCKER_FLAGS=-p 9230:9230
      - GATEWAY_LISTEN=:4566
      - DOCKER_HOST=unix:///var/run/docker.sock

    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
